[build]
base = "/"
publish = "dist"
command = "mkdir -p dist && cp -r . dist/"

[build.environment]
NODE_VERSION = "18"

[context.production]
command = "mkdir -p dist && cp -r . dist/"
publish = "dist"

[context.deploy-preview]
command = "mkdir -p dist && cp -r . dist/"
publish = "dist"

[context.branch-deploy]
command = "mkdir -p dist && cp -r . dist/"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
