[build]
base = "/"
publish = "dist"
command = "if not exist dist mkdir dist && xcopy /E /I /Y * dist"

[build.environment]
NODE_VERSION = "18"

[context.production]
command = "if not exist dist mkdir dist && xcopy /E /I /Y * dist"
publish = "dist"

[context.deploy-preview]
command = "if not exist dist mkdir dist && xcopy /E /I /Y * dist"
publish = "dist"

[context.branch-deploy]
command = "if not exist dist mkdir dist && xcopy /E /I /Y * dist"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
