[build]
base = "/"
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[context.production]
command = "npm run build"
publish = "dist"

[context.deploy-preview]
command = "npm run build"
publish = "dist"

[context.branch-deploy]
command = "npm run build"
publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add a catch-all redirect for any path
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure the root path works
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
