[build]
base = "/"
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[context.production]
command = "npm run build"
publish = "dist"

[context.deploy-preview]
command = "npm run build"
publish = "dist"

[context.branch-deploy]
command = "npm run build"
publish = "dist"

[[redirects]]
  from = "/*"
  to = "/splash.html"
  status = 200
from = "/*"
to = "/splash.html"
status = 200
